### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by benkoshy** [TrimbleSolutionsCorporation/TeklaApplicationLibrary#2]
Hi there development team

thank you for providing this library.

Do you have any code examples by which we can use this library? It would be extremely beneficial to developers if this could be provided. I note that on the front page there is a 'hello world' link but this goes to github and doesn't have any tekla specific examples?

rgds

Ben

**Comment by CarlosHerrero** [comment]
Hello Ben,

The link to HelloWorld page was a mistake. This library was created during the years by different Tekla Structures extension developers and teams, and lacks proper documentation, tests and examples. Because it shows how to use Open API for some common operations it was decided to publish it as open source. There are no plans to update this project but to create a new one with better organization and documentation.

Regards,
Carlos
